# -*- coding: utf-8 -*-
"""random practice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v1P2QkcF4PMdemc0cnS_qrOgE2lAXy4t
"""

import requests
import pandas as pd
from bs4 import BeautifulSoup
book_name = []
price = []
book_availability = []
print(book_name)
url = "https://books.toscrape.com/catalogue/page-1.html"

html = requests.get(url).content

html_tree = BeautifulSoup(html, "html.parser")
for itr in range(1, 51):
    url = f"https://books.toscrape.com/catalogue/page-{itr}.html"

    html = requests.get(url).content

    html_tree = BeautifulSoup(html, "html.parser")

    book = html_tree.find_all(class_ = "thumbnail")

    book = [item.get("alt") for item in book]
    book_name = book_name + book


    book_price = html_tree.find_all(class_ = "price_color")

    book_price = [items.text for items in book_price]
    book_price = [items.replace("£","") for items in book_price]
    price = price + book_price




    availability = html_tree.find_all(class_ = "instock availability")

    availability = [items.text for items in availability]

    # availability

    availability = [items.replace("\n","") for items in availability]

    # availability

    availability = [items.strip() for items in availability]

    book_availability = book_availability + availability



# print(book_name)
data = {
    "Name" : book_name,
    "Price" : price,
    "Availability" : book_availability
}

print(len(book_name),"\n",len(price),'\n',len(book_availability))
df = pd.DataFrame(data)
print(df)
df.to_excel("alldata.xlsx")

